import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';import {pool} from './db.js';
const hash=value=>createHash('sha256').update(value).digest('hex');
const same=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)};
const secure=process.env.NODE_ENV==='production';
const sessionCookie={httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:7*86400*1000};
const stateCookie={httpOnly:true,secure,sameSite:'lax',path:'/auth/github/callback',maxAge:10*60*1000};
function config(){if(!process.env.GITHUB_CLIENT_ID||!process.env.GITHUB_CLIENT_SECRET||!process.env.GITHUB_OWNER_ID||!process.env.PUBLIC_ORIGIN)throw Error('OAuth configuration missing');return {clientId:process.env.GITHUB_CLIENT_ID,secret:process.env.GITHUB_CLIENT_SECRET,ownerId:Number(process.env.GITHUB_OWNER_ID),origin:new URL(process.env.PUBLIC_ORIGIN).origin}}
export function startGithub(req,res){const {clientId,origin}=config();const state=randomBytes(24).toString('base64url');res.cookie('jobtrail_oauth_state',state,stateCookie);const callback=new URL('/auth/github/callback',origin);const url=new URL('https://github.com/login/oauth/authorize');url.searchParams.set('client_id',clientId);url.searchParams.set('redirect_uri',callback.href);url.searchParams.set('state',state);res.redirect(url.href)}
export async function githubCallback(req,res){const {clientId,secret,ownerId,origin}=config();const state=req.cookies?.jobtrail_oauth_state;res.clearCookie('jobtrail_oauth_state',{path:'/auth/github/callback',secure,sameSite:'lax'});
 if(!state||typeof req.query.state!=='string'||!same(state,req.query.state)||typeof req.query.code!=='string')return res.status(400).send('Invalid login state');
 const reply=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:clientId,client_secret:secret,code:req.query.code,redirect_uri:new URL('/auth/github/callback',origin).href}),signal:AbortSignal.timeout(10000)});if(!reply.ok)throw Error('GitHub OAuth exchange failed');const body=await reply.json();if(!body.access_token)throw Error('GitHub OAuth access denied');
 const userResponse=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${body.access_token}`,Accept:'application/vnd.github+json','User-Agent':'JobTrail'},signal:AbortSignal.timeout(10000)});if(!userResponse.ok)throw Error('GitHub identity check failed');const user=await userResponse.json();if(!Number.isSafeInteger(ownerId)||user.id!==ownerId)return res.status(403).send('This account is not allowed');
 const token=randomBytes(32).toString('base64url');await pool.query('INSERT INTO jobtrail_sessions(token_hash,expires_at) VALUES($1,now()+interval \'7 days\')',[hash(token)]);res.cookie('jobtrail_session',token,sessionCookie);res.redirect('/')}
export async function auth(req,res,next){try{const token=req.cookies?.jobtrail_session;if(!token)return res.status(401).json({error:'Sign in required'});const {rows}=await pool.query('SELECT 1 FROM jobtrail_sessions WHERE token_hash=$1 AND expires_at>now()',[hash(token)]);if(!rows.length)return res.status(401).json({error:'Session expired'});req.sessionHash=hash(token);next()}catch(e){next(e)}}
export async function logout(req,res){await pool.query('DELETE FROM jobtrail_sessions WHERE token_hash=$1',[req.sessionHash]);res.clearCookie('jobtrail_session',{path:'/',secure,sameSite:'lax'});res.json({ok:true})}
