import 'dotenv/config';import express from 'express';import cookieParser from 'cookie-parser';import {fileURLToPath} from 'node:url';import {dirname,join} from 'node:path';import {ZodError} from 'zod';import {pool,migrate} from './db.js';import {startGithub,githubCallback,auth,logout} from './auth.js';import {profileSchema,tailor} from './engine.js';import {renderResume} from './pdf.js';import {jobs} from './jobs.js';
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'150kb'}));app.use(cookieParser());app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Cache-Control','no-store');if(req.method==='GET'||req.method==='HEAD'||req.method==='OPTIONS')return next();const expected=process.env.PUBLIC_ORIGIN&&new URL(process.env.PUBLIC_ORIGIN).origin;if(!expected||req.get('Origin')!==expected)return res.status(403).json({error:'Origin check failed'});next()});
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
app.get('/health',(_,res)=>res.json({ok:true,phase:'owner-only-beta'}));
app.get('/auth/github',wrap(startGithub));app.get('/auth/github/callback',wrap(githubCallback));app.get('/api/me',auth,(req,res)=>res.json({ok:true}));app.post('/auth/logout',auth,wrap(logout));
app.get('/api/profile',auth,wrap(async(req,res)=>{const {rows:[row]}=await pool.query('SELECT profile,profile_revision FROM jobtrail_owner WHERE id=1');res.json({profile:row?.profile||null,revision:row?.profile_revision||0})}));
app.put('/api/profile',auth,wrap(async(req,res)=>{const profile=profileSchema.parse(req.body?.profile);const {rows:[row]}=await pool.query(`INSERT INTO jobtrail_owner(id,profile,profile_revision) VALUES(1,$1::jsonb,1)
 ON CONFLICT(id) DO UPDATE SET profile=EXCLUDED.profile,profile_revision=jobtrail_owner.profile_revision+1,updated_at=now() RETURNING profile_revision`,[JSON.stringify(profile)]);res.json({saved:true,revision:row.profile_revision})}));
app.post('/api/resume',auth,wrap(async(req,res)=>{const {rows:[owner]}=await pool.query('SELECT profile FROM jobtrail_owner WHERE id=1');if(!owner?.profile)return res.status(409).json({error:'Save your master profile first'});const tailored=tailor({profile:owner.profile,job:req.body?.job});const pdf=await renderResume(tailored);res.type('application/pdf');res.setHeader('Content-Disposition','attachment; filename="tailored-resume.pdf"');res.send(pdf)}));
app.get('/api/jobs',auth,wrap(async(req,res)=>res.json(await jobs(req.query.q||'python developer'))));
app.get('/api/tracker',auth,wrap(async(req,res)=>{const {rows}=await pool.query('SELECT id,title,company,application_url,source,status,profile_revision,created_at,updated_at FROM jobtrail_applications ORDER BY updated_at DESC LIMIT 100');res.json({applications:rows})}));
app.put('/api/tracker/:id',auth,wrap(async(req,res)=>{const data=req.body||{};if(typeof req.params.id!=='string'||req.params.id.length>500||!['saved','applied','interview','offer','rejected','withdrawn'].includes(data.status)||typeof data.title!=='string'||data.title.length<2||data.title.length>200||typeof data.company!=='string'||data.company.length>150||typeof data.source!=='string'||data.source.length>80||typeof data.description!=='string'||data.description.length>25000)return res.status(400).json({error:'Invalid job or status'});
 let url;try{url=new URL(data.url);if(url.protocol!=='https:')throw Error()}catch{return res.status(400).json({error:'Invalid apply URL'})};const {rows:[owner]}=await pool.query('SELECT profile_revision FROM jobtrail_owner WHERE id=1');if(!owner)return res.status(409).json({error:'Save your profile first'});
 await pool.query(`INSERT INTO jobtrail_applications(id,title,company,application_url,source,status,job_description,profile_revision) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
 ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,company=EXCLUDED.company,application_url=EXCLUDED.application_url,source=EXCLUDED.source,status=EXCLUDED.status,job_description=EXCLUDED.job_description,profile_revision=EXCLUDED.profile_revision,updated_at=now()`,[req.params.id,data.title,data.company,url.href,data.source,data.status,data.description,owner.profile_revision]);res.json({saved:true})}));
app.use(express.static(join(dirname(fileURLToPath(import.meta.url)),'../public'),{index:'index.html',setHeaders:r=>r.setHeader('Cache-Control','no-store')}));
app.use((err,req,res,next)=>{console.error('request.failed',err);if(res.headersSent)return next(err);if(err instanceof ZodError)return res.status(400).json({error:'Invalid profile or job description',issues:err.issues.map(x=>({path:x.path,message:x.message}))});res.status(err.status||500).json({error:err.status?err.message:'Server error'})});
if(process.argv[1]===fileURLToPath(import.meta.url)){if(!process.env.DATABASE_URL||!process.env.PUBLIC_ORIGIN||!process.env.GITHUB_CLIENT_ID||!process.env.GITHUB_CLIENT_SECRET||!process.env.GITHUB_OWNER_ID){console.error('Required database, origin, or OAuth setting missing');process.exit(1)}migrate().then(()=>app.listen(process.env.PORT||3000,()=>console.log('JobTrail ready'))).catch(err=>{console.error('Migration failed',err);process.exit(1)})}
export default app;
